{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "simpleswe.fullname" . }}
  namespace: {{ include "simpleswe.namespace" . }}
  labels:
    {{- include "simpleswe.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "simpleswe.selectorLabels" . | nindent 6 }}
{{- end }}
