apiVersion: v1
kind: Service
metadata:
  name: {{ include "simpleswe.fullname" . }}
  namespace: {{ include "simpleswe.namespace" . }}
  labels:
    {{- include "simpleswe.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "simpleswe.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
