apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "simpleswe.serviceAccountName" . }}
  namespace: {{ include "simpleswe.namespace" . }}
  labels:
    {{- include "simpleswe.labels" . | nindent 4 }}
automountServiceAccountToken: true
